export default {
  currentContent: {
    "id": 0,
    "type": "navPage",
    "pagnation": false,
    "productBox": true,
    "slider": true,
    "category": "featured",
    "boxStyle": "horizontal5",
    "primaryTitle": true,
    "secondaryTitle": false,
    "fullTitle": "FEATURED PRODUCTS",
    "subTitle1": "FEATURED",
    "subTitle2": "PRODUCTS",
    "contactBox": false
  },
  contents: [{
    "id": 0,
    "type": "navPage",
    "pagnation": false,
    "productBox": true,
    "slider": true,
    "category": "featured",
    "boxStyle": "horizontal5",
    "primaryTitle": true,
    "secondaryTitle": false,
    "fullTitle": "FEATURED PRODUCTS",
    "subTitle1": "FEATURED",
    "subTitle2": "PRODUCTS",
    "contactBox": false
  }, {
    "id": 1,
    "type": "navPage",
    "pagnation": true,
    "productBox": true,
    "slider": false,
    "category": "carBumpers",
    "boxStyle": "horizontal5",
    "primaryTitle": false,
    "secondaryTitle": true,
    "fullTitle": "CAR BUMPERS",
    "subTitle1": "CAR",
    "subTitle2": "BUMPERS",
    "contactBox": false
  }, {
    "id": 2,
    "type": "navPage",
    "pagnation": true,
    "productBox": true,
    "slider": false,
    "category": "headlights",
    "boxStyle": "horizontal5",
    "primaryTitle": false,
    "secondaryTitle": true,
    "fullTitle": "CAR HEADLIGHTS",
    "subTitle1": "CAR",
    "subTitle2": "HEADLIGHTS",
    "contactBox": false
  }, {
    "id": 3,
    "type": "navPage",
    "pagnation": true,
    "productBox": true,
    "slider": false,
    "category": "carWheels",
    "boxStyle": "horizontal5",
    "primaryTitle": false,
    "secondaryTitle": true,
    "fullTitle": "CAR WHEELS",
    "subTitle1": "CAR",
    "subTitle2": "WHEELS",
    "contactBox": false
  }, {
    "id": 4,
    "type": "navPage",
    "pagnation": true,
    "productBox": true,
    "slider": false,
    "category": "carAudio",
    "boxStyle": "vertical4",
    "primaryTitle": false,
    "secondaryTitle": true,
    "fullTitle": "CAR AUDIO SYSTEMS",
    "subTitle1": "CAR",
    "subTitle2": "AUDIO SYSTEMS",
    "contactBox": false
  }, {
    "id": 5,
    "type": "navPage",
    "pagnation": true,
    "productBox": true,
    "slider": false,
    "category": "truckBumpers",
    "boxStyle": "horizontal5",
    "primaryTitle": false,
    "secondaryTitle": true,
    "fullTitle": "TRUCK BUMPERS",
    "subTitle1": "TRUCK",
    "subTitle2": "BUMPERS",
    "contactBox": false
  }, {
    "id": 6,
    "type": "navPage",
    "pagnation": false,
    "productBox": false,
    "slider": false,
    "category": false,
    "boxStyle": false,
    "primaryTitle": false,
    "secondaryTitle": false,
    "fullTitle": "CONTACT",
    "subTitle1": false,
    "subTitle2": false,
    "contactBox": true
  }, {
    "id": 101,
    "type": "singleProduct",
    "imgUrl": "/images/h1.jpg",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$512.00",
    "special": false
  }, {
    "id": 102,
    "type": "singleProduct",
    "imgUrl": "/images/h2.jpg",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
		"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special": false
  }, {
    "id": 103,
    "type": "singleProduct",
    "imgUrl": "/images/h3.jpg",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
		"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special": false
  }, {
    "id": 104,
    "type": "singleProduct",
    "imgUrl": "/images/h4.jpg",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
		"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$500.00",
    "special": false
  }, {
    "id": 105,
    "type": "singleProduct",
    "imgUrl": "/images/h5.jpg",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
		"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special": false
  }, {
    "id": 106,
    "type": "singleProduct",
    "imgUrl": "/images/h3.jpg",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
		"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$600.00",
    "special": "$512.00"
  }, {
    "id": 107,
    "type": "singleProduct",
    "imgUrl": "/images/h2.jpg",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
		"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$400.00",
    "special": "$352.00"
  }, {
    "id": 108,
    "type": "singleProduct",
    "imgUrl": "/images/g7.png",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
		"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special": "$202.00"
  }, {
    "id": 109,
    "type": "singleProduct",
    "imgUrl": "/images/h1.jpg",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
		"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$400.00",
    "special": "$322.00"
  }, {
    "id": 110,
    "type": "singleProduct",
    "imgUrl": "/images/h5.jpg",
    "category": "headlights",
    "name": "Lorem Ipsum is simply",
		"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$700.00",
    "special": "$602.00"
  }, {
    "id": 111,
    "type": "singleProduct",
    "imgUrl": "/images/b1.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$512.00",
    "special": false
  }, {
    "id": 112,
    "type": "singleProduct",
    "imgUrl": "/images/b2.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special": false
  }, {
    "id": 113,
    "type": "singleProduct",
    "imgUrl": "/images/b3.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special": false
  }, {
    "id": 114,
    "type": "singleProduct",
    "imgUrl": "/images/b4.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$500.00",
    "special": false
  }, {
    "id": 115,
    "type": "singleProduct",
    "imgUrl": "/images/b5.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special": false
  }, {
    "id": 116,
    "type": "singleProduct",
    "imgUrl": "/images/b6.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$600.00",
    "special": "$512.00"
  }, {
    "id": 117,
    "type": "singleProduct",
    "imgUrl": "/images/b7.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$400.00",
    "special": "$352.00"
  }, {
    "id": 118,
    "type": "singleProduct",
    "imgUrl": "/images/b8.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special": "$202.00"
  }, {
    "id": 119,
    "type": "singleProduct",
    "imgUrl": "/images/b4.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$400.00",
    "special": "$322.00"
  }, {
    "id": 120,
    "type": "singleProduct",
    "imgUrl": "/images/b1.jpg",
    "category": "carBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$700.00",
    "special": "$602.00"
  }, {
    "id": 121,
    "type": "singleProduct",
    "imgUrl": "/images/t1.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$512.00",
    "special": false
  }, {
    "id": 122,
    "type": "singleProduct",
    "imgUrl": "/images/t2.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special": false
  }, {
    "id": 123,
    "type": "singleProduct",
    "imgUrl": "/images/t3.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special": false
  }, {
    "id": 124,
    "type": "singleProduct",
    "imgUrl": "/images/t4.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$500.00",
    "special": false
  }, {
    "id": 125,
    "type": "singleProduct",
    "imgUrl": "/images/t5.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special": false
  }, {
    "id": 126,
    "type": "singleProduct",
    "imgUrl": "/images/t6.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$600.00",
    "special": "$512.00"
  }, {
    "id": 127,
    "type": "singleProduct",
    "imgUrl": "/images/t7.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$400.00",
    "special": "$352.00"
  }, {
    "id": 128,
    "type": "singleProduct",
    "imgUrl": "/images/t1.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special": "$202.00"
  }, {
    "id": 129,
    "type": "singleProduct",
    "imgUrl": "/images/t4.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$400.00",
    "special": "$322.00"
  }, {
    "id": 130,
    "type": "singleProduct",
    "imgUrl": "/images/t1.jpg",
    "category": "carWheels",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$700.00",
    "special": "$602.00"
  }, {
    "id": 131,
    "type": "singleProduct",
    "imgUrl": "/images/b1.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$512.00",
    "special": false
  }, {
    "id": 132,
    "type": "singleProduct",
    "imgUrl": "/images/b2.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special": false
  }, {
    "id": 133,
    "type": "singleProduct",
    "imgUrl": "/images/b3.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special": false
  }, {
    "id": 134,
    "type": "singleProduct",
    "imgUrl": "/images/b4.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$500.00",
    "special": false
  }, {
    "id": 135,
    "type": "singleProduct",
    "imgUrl": "/images/b5.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special": false
  }, {
    "id": 136,
    "type": "singleProduct",
    "imgUrl": "/images/b6.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$600.00",
    "special": "$512.00"
  }, {
    "id": 137,
    "type": "singleProduct",
    "imgUrl": "/images/b7.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$400.00",
    "special": "$352.00"
  }, {
    "id": 138,
    "type": "singleProduct",
    "imgUrl": "/images/b8.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special": "$202.00"
  }, {
    "id": 139,
    "type": "singleProduct",
    "imgUrl": "/images/b4.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$400.00",
    "special": "$322.00"
  }, {
    "id": 140,
    "type": "singleProduct",
    "imgUrl": "/images/b1.jpg",
    "category": "truckBumpers",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$700.00",
    "special": "$602.00"
  }, {
    "id": 141,
    "type": "singleProduct",
    "imgUrl": "/images/g3.png",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$512.00",
    "special" : false
  }, {
    "id": 142,
    "type": "singleProduct",
    "imgUrl": "/images/g1.jpg",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special" : false
  }, {
    "id": 143,
    "type": "singleProduct",
    "imgUrl": "/images/g2.jpg",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special" : false
  }, {
    "id": 144,
    "type": "singleProduct",
    "imgUrl": "/images/g3.png",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$500.00",
    "special" : false
  }, {
    "id": 145,
    "type": "singleProduct",
    "imgUrl": "/images/g4.jpg",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$120.00",
    "special" : false
  }, {
    "id": 146,
    "type": "singleProduct",
    "imgUrl": "/images/g1.jpg",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$600.00",
    "special": "$512.00"
  }, {
    "id": 147,
    "type": "singleProduct",
    "imgUrl": "/images/g6.jpg",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "400$.00",
    "special": "$352.00"
  }, {
    "id": 148,
    "type": "singleProduct",
    "imgUrl": "/images/g7.png",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$300.00",
    "special": "$202.00"
  }, {
    "id": 149,
    "type": "singleProduct",
    "imgUrl": "/images/g8.png",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$400.00",
    "special": "$322.00"
  }, {
    "id": 150,
    "type": "singleProduct",
    "imgUrl": "/images/g1.jpg",
    "category": "featured",
    "name": "Lorem Ipsum is simply",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, in reprehenderit.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$700.00",
    "special": "$602.00"
  }, {
    "id": 151,
    "type": "singleProduct",
    "imgUrl": "/images/a1.jpg",
    "category": "carAudio",
    "name": "Fondmetal 7500",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$502.00",
    "special" : false
  }, {
    "id": 152,
    "type": "singleProduct",
    "imgUrl": "/images/a2.jpg",
    "category": "carAudio",
    "name": "Fondmetal 7500",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$502.00",
    "special" : false
  }, {
    "id": 153,
    "type": "singleProduct",
    "imgUrl": "/images/a3.jpg",
    "category": "carAudio",
    "name": "Fondmetal 7500",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$502.00",
    "special" : false
  }, {
    "id": 154,
    "type": "singleProduct",
    "imgUrl": "/images/g6.jpg",
    "category": "carAudio",
    "name": "Fondmetal 7500",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "descriptionLong": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "price": "$502.00",
    "special" : false
  }]
};